DATABASE_TIME_WITHOUT_MISSINGS_FILENAME = "./Preprocessing/data/database_time_without_missings.csv"
DATABASE_PANELTIME_WITHOUT_MISSINGS_FILENAME = "./Preprocessing/data/database_paneltime_without_missings.csv"
DATABASE_PANELTIME_WITH_MISSINGS_FILENAME = "./Preprocessing/data/database_paneltime_with_missings.csv"
DATABASE_PANELTIME_AS_MISSINGS_FILENAME = "./Preprocessing/data/database_paneltime_as_missings.csv"
TEST_TIME_FILENAME = "./Preprocessing/data/test_time_database.csv"
TEST_PANEL_FILENAME = "./Preprocessing/data/test_panel_database.csv"
TEST_PANELTIME_FILENAME = "./Preprocessing/data/test_paneltime_database.csv"
TEST_MISSING_FILENAME = "./Preprocessing/data/test_missing_database.csv"
