VARIABLES_NOT_DEFINED = "variables are not defined"
TIME_VARIABLE_INEXISTENT = "selected time variable does not exists"
INVALID_METHOD = "invalid method, must be :fast (32b) or :precise"
SELECTED_VARIABLES_DOES_NOT_EXISTS = "selected variables does not exists"
SOME_VARIABLES_NOT_FOUND = "some variables were not found"