const KFOLDCROSSVALIDATION_DEFAULT = false
const NUMFOLDS_DEFAULT = 5
const TESTSETSHARE_DEFAULT = 0.15
const VALID_PRELIMINARYSELECTION = [:lasso]
const EXPORTCSV_DEFAULT = nothing
const EXPORTSUMMARY_DEFAULT = nothing
