DATA_NOT_DEFINED = "data parameter is not defined"
OUTSAMPLE_LOWER_VALUE = "outsample parameter must be greater than 0"
OUTSAMPLE_HIGHER_VALUE = "outsample parameter must be lower than the number of observations"
CSV_DUPLICATED_PARAMETERS = "resultscsv and csv parameters are defined at the same time"
NO_ENOUGH_OBSERVATIONS = "there is no enough observations"
SELECTED_VARIABLES_DOES_NOT_EXISTS = "selected variables does not exists"
